onlyBuiltDependencies:
  - "@parcel/watcher"
  - sharp
allowBuilds:
  "@parcel/watcher": true
  core-js: false
  esbuild: false
  msw: false
  protobufjs: false
  puppeteer: true
  sharp: true
  workerd: false
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - shadcn
  - "@base-ui/*"
